language: php
dist: trusty

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - nightly

install:
  - composer install

script:
  - ./vendor/bin/phpunit